// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evtvvfuxqkbsnduxwhfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dHZ2ZnV4cWtic25kdXh3aGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTAyNjAsImV4cCI6MjA2ODkyNjI2MH0.b8A2lSjm6UGdH3cSSXpiTn0C6hY3YQykMEgBXAB-fF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});